---

- name: Open port 80 on firewall
  iptables:
    chain: "INPUT"
    protocol: "tcp"
    destination_port: 80
    jump: "ACCEPT"
  tags:
    - install
    - apache

- name: Ensure Apache is installed
  yum:
    name: "httpd24"
    state: "installed"
  tags:
    - install
    - apache

- name: Enable apache on startup
  service:
    name: "httpd"
    enabled: yes
    state: "restarted"
  tags:
    - install
    - apache
