---

- name: Add Kibana repo
  copy:
    src: "kibana.repo"
    dest: "/etc/yum.repos.d/kibana.repo"

- name: Install Kibana package
  yum:
    name: "kibana"
    state: "latest"

- name: Open kibana port (iptables)
  iptables:
    chain: "INPUT"
    protocol: "tcp"
    destination_port: 5601
    jump: "ACCEPT"
