---

- name: Download apache and php
  apt:
    update_cache: "yes"
    name: "{{ item }}"
    state: "latest"
  with_items:
    - apache2
    - php5
    - php5-mysql

- name: Open port 80 on iptables
  iptables:
    chain: "INPUT"
    protocol: "tcp"
    destination_port: 80
    jump: "ACCEPT"

- name: Enable mod rewrite
  shell:
    "a2enmod rewrite"

- name: Enable ssl
  shell:
    "a2enmod ssl"

- name: Enable apache on startup
  service:
    name: "apache2"
    enabled: yes
    state: "restarted"
